name: pangeo-workflow-examples
channels:
  - conda-forge
dependencies:
  - mamba
  - pip
  - python=3.10
  - ca-certificates
  - certifi
  - eodag
  - ipykernel
  - openssl
  - odc-stac
  - pystac-client
