name: pangeo-workflow-examples
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - mamba
  - ipykernel
  - ca-certificates
  - certifi
  - ipykernel
  - openssl
  - odc-stac
  - pystac-client
  - pip:
    - eodag
